### ISSUE TITLE
Postgres DB incompatibility

### ISSUE THREAD

**Issue by soerface** [flipdot/drinks-touch#220]
With #218, the repository was upgraded from Postgres 16 to Postgres 17.

Locally, I receive this error message when starting my dev environment:

> postgres-1    | PostgreSQL Database directory appears to contain a database; Skipping initialization
> postgres-1    | 
> postgres-1    | 2024-09-29 15:51:28.689 UTC [1] FATAL:  database files are incompatible with server
> postgres-1    | 2024-09-29 15:51:28.689 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 17.0 (Debian 17.0-1.pgdg120+1).

Locally I can easily resolve this by dropping the DB. However, I'm wondering what the plan is for our prod environment. What will happen if we install the new version? Is there a guide to perform the upgrade? Was our installation already upgraded?

FYI @malled2002 @dargmuesli

**Comment by dargmuesli** [comment]
We could at some point maybe even use `alpine` postgres images, I've initiated work to support the dockerized upgrade path for those yesterday:

- https://github.com/tianon/docker-postgres-upgrade/pull/108

**Comment by malled2002** [comment]
>  I'm wondering what the plan is for our prod environment. 

AFAIK: Our prod setup is using salt instead of docker. So the this upgrade only affects dev as long we stay on salt deployment

**Comment by soerface** [comment]
In this case I would vote for aligning the version that we have in salt with the version that's here in compose. Do you know whoch

**Comment by dargmuesli** [comment]
🧂

**Comment by soerface** [comment]
lol seems I can't use GitHub from mobile, accidentally sent message too early and closed the issue.

Well we could also leave it at 17 locally to see if something breaks in dev. Just shouldn't accidentally use Postgres 17 features but honestly that didn't yet happen to me, I don't even know what's new in each new postgres version.

**Comment by dargmuesli** [comment]
Just some performance improvements, changes to some JSON stuff, better replication and some security features, nothing too worrisome.
