### ISSUE TITLE
Fill TODOs in README

### ISSUE THREAD

**Issue by dargmuesli** [flipdot/drinks-touch#24]
There are TODOs in the README. Either remove or do them.

**Comment by cfstras** [comment]
Licensing: I would propose GPLv2.
need ack from @GameScripting @soerface @malled2002 @kmein @nox-x

**Comment by GameScripting** [comment]
GPLv2 is fine for me.

**Comment by soerface** [comment]
I'm fine with GPLv2, MIT, BSD

**Comment by anuejn** [comment]
gpl v2 is legacy and should not be eused for new software. why not v3?

**Comment by Dargmuesli** [comment]
Yo @malled2002 @kmein @nox-x what about you?
I have no preference regarding licensing.
