### ISSUE TITLE
Rename Project

### ISSUE THREAD

**Issue by dargmuesli** [flipdot/drinks-touch#50]
Why isn't this repository called `drinks-touch` like the domain it's available at?

**Comment by dargmuesli** [comment]
I'm basically asking whether I can rename this project or whether something speaks against it.

**Comment by cfstras** [comment]
I‘d say we just go all the way and call it „drinks“?  or is that too short?

**Comment by dargmuesli** [comment]
I'd vote for a name that is more specific so that it's clear right away to which project this repository belongs. I've had the case where I searched for the flipdot repository in which different versions of our logo were stored and I couldn't find it right away because of an undescriptive name. Also `drinks-touch` would separate it from future projects that eg. may deal with `drinks-orders`or something alike. `drinks` would be different too, yes, but I don't see why the scanner repo was more important than other drink related repos, even if you could argue that it was "the first" or "the largest" at this time.
